# Generated by Django 2.2.4 on 2019-09-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('release_date', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('model', models.CharField(max_length=20)),
                ('screen_size', models.IntegerField()),
                ('resolution', models.CharField(max_length=25)),
                ('dimensions', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('ram', models.CharField(max_length=10)),
                ('storage', models.CharField(max_length=10)),
                ('rear_camera', models.CharField(max_length=40)),
                ('front_camera', models.CharField(max_length=40)),
            ],
        ),
    ]
