# Generated by Django 2.2.4 on 2019-09-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('release_date', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=200)),
                ('screen_size', models.IntegerField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=25, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('ram', models.CharField(blank=True, max_length=10, null=True)),
                ('storage', models.CharField(blank=True, max_length=10, null=True)),
                ('rear_camera', models.CharField(blank=True, max_length=20, null=True)),
                ('front_camera', models.CharField(blank=True, max_length=20, null=True)),
                ('score', models.CharField(blank=True, max_length=10, null=True)),
                ('shop', models.CharField(max_length=30)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('exact_model', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
