# Generated by Django 2.2.4 on 2019-09-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='price',
            field=models.CharField(max_length=15),
        ),
    ]
